// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

StructuredBuffer<float3> vertices;
RWStructuredBuffer<float> heights;
uint numVertices;
float testValue = 100;

[numthreads(512,1,1)]
void CSMain (uint id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    if (id >= numVertices) { return; }
    float3 vertexPos = vertices[id];
    heights[id] = 1 + sin(vertexPos.y * testValue) * 0.05;
    

}
